** Generating the descriptive data in Figure 1 and table 1

** BE SURE TO REPLCE [directory] WITH YOUR WORKING DIRECTORY where you saved the replication files

clear

** open the raw version of the SEAD dataset 

use "[directory]\Approval data for SEAD v1.dta"

** table 1: Description of the SEAD dataset

* I used a lot of copying and pasting of results to generate the table, but the data are generated very easily and then you cut and paste them in from your screen. 

* columns 1-3 are from tabulating the dummy variable of whether a survey is from JAR or not and the state variable, changing the order of the columns

tab state jar

* columns 4 and 5 are the range of each year by state, so get the range of the variable and keep the coumns for min and max

by state: sum year

* column 6 is the rumber of data series. This is easily generated by collapsing the data by series and state (collapsing on year because all observations have a value for it). The number of observations for each state that remains is the number of unique series. 

preserve

collapse year, by(variable state)

tab state

restore


** Figure 1: survey marginals by year

set scheme s2mono

histogram year, bin(74) frequency xlabel(1947(4)2019, angle(vertical)) ylabel(,nogrid) ytitle(Frequency) xtitle(Year) graphregion(fcolor(white) ifcolor(white) lcolor(none) ilcolor(none)) 

graph save "Graph" "[directory]\Figure 1.gph", replace